export const GET_ALL_CATEGORY = 'GET_ALL_CATEGORY'
export const CREATE_CATE= 'CREATE_CATE'

export const GET_ERROR = 'GET_ERROR'

export const GET_ALL_BRAND = 'BRAND'
export const CREATE_BRAND = 'CREATE_BRAND'


export const CREATE_SUB_CATE = 'CREATE_SUB_CATE'

export const CREATE_NEW_USER = 'CREATE_NEW_USER'

export const LOGIN_USER = 'LOGIN_USER'
export const FORGET_PASSWORD = 'FORGET_PASSWORD'
export const VERFIY_PASSWORD = 'VERFIY_PASSWORD'
export const RESET_PASSWORD = 'RESET_PASSWORD'
export const GET_SUB_DEPENDED = 'GET_SUB_DEPENDED'
export const CREATE_PRODUCT = 'CREATE_PRODUCT'
export const GET_ALL_PRODUCT = 'GET_ALL_PRODUCT'
export const GET_PRODUCT_DETALIS = 'GET_PRODUCT_DETALIS'
export const GET_ONE_CATEGORY = 'GET_ONE_CATEGORY'
export const GET_PRODUCT_LIKE = 'GET_PRODUCT_LIKE'
